nohup: ignoring input
127.0.0.1 - - [31/May/2025 20:28:46] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [31/May/2025 20:30:06] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [31/May/2025 20:30:06] "GET /styles.css HTTP/1.1" 200 -
127.0.0.1 - - [31/May/2025 20:30:06] "GET /app.js HTTP/1.1" 304 -
127.0.0.1 - - [31/May/2025 20:34:46] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [31/May/2025 20:34:46] "GET /styles.css HTTP/1.1" 304 -
127.0.0.1 - - [31/May/2025 20:34:46] "GET /app.js HTTP/1.1" 304 -
127.0.0.1 - - [31/May/2025 20:35:42] "GET /styles.css HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 37996)
Traceback (most recent call last):
  File "/usr/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.12/http/server.py", line 1311, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/usr/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/lib/python3.12/http/server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.12/http/server.py", line 878, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.12/shutil.py", line 204, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [31/May/2025 20:36:21] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [31/May/2025 20:36:21] code 404, message File not found
127.0.0.1 - - [31/May/2025 20:36:21] "GET /favicon.ico HTTP/1.1" 404 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 38590)
Traceback (most recent call last):
  File "/usr/lib/python3.12/http/server.py", line 731, in send_head
    f = open(path, 'rb')
        ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/vboxuser/Desktop/todo_api/frontend/favicon.ico'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.12/http/server.py", line 1311, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/usr/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/lib/python3.12/http/server.py", line 676, in do_GET
    f = self.send_head()
        ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/server.py", line 733, in send_head
    self.send_error(HTTPStatus.NOT_FOUND, "File not found")
  File "/usr/lib/python3.12/http/server.py", line 491, in send_error
    self.wfile.write(body)
  File "/usr/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [31/May/2025 20:37:09] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [31/May/2025 20:37:09] "GET /styles.css HTTP/1.1" 200 -
127.0.0.1 - - [31/May/2025 20:37:09] "GET /app.js HTTP/1.1" 304 -
127.0.0.1 - - [31/May/2025 20:48:25] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [31/May/2025 20:48:25] "GET /styles.css HTTP/1.1" 304 -
127.0.0.1 - - [31/May/2025 20:48:25] "GET /app.js HTTP/1.1" 304 -
127.0.0.1 - - [31/May/2025 20:49:08] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 49658)
Traceback (most recent call last):
  File "/usr/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.12/http/server.py", line 1311, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/usr/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/lib/python3.12/http/server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.12/http/server.py", line 878, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.12/shutil.py", line 204, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [31/May/2025 20:52:05] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [31/May/2025 20:52:05] "GET /styles.css HTTP/1.1" 304 -
127.0.0.1 - - [31/May/2025 20:55:22] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 34466)
Traceback (most recent call last):
  File "/usr/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.12/http/server.py", line 1311, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/usr/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/lib/python3.12/http/server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.12/http/server.py", line 878, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.12/shutil.py", line 204, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
127.0.0.1 - - [31/May/2025 20:55:22] "GET /app.js HTTP/1.1" 200 -
